baseurl: ""
url: https://evomortgagesolutions.co.za
lang: en-ZA

title: evo Mortgage Solutions - Bond Origination & Home Loans | Pretoria
email: verna.vanheerden@evogroup.co.za
phone: "+27834476674"
description: Get expert home loan and bond origination assistance from evo Mortgage Solutions in Pretoria. Compare bank quotes, get pre-qualified, and secure competitive home finance with experienced property finance specialists.
author: Eben Roux / Pieter Oosthuizen

analytics:
  google: xxx

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/img/logo/logo.png

exclude: [node_modules, webpack-config.js, package.json, package-lock.json]

group: evo Homeloans

company: evo Mortgage Solutions

address: 662 Hofmeyer Street, Wingate Park, Pretoria, 0017
